version: "3.9"
services: 
  ## OLLAMA - Service

  ## OLLAMA - Instance

  ## WHATSAPP - WAHA

  ## WHATSAPP - Service

  ## INTERLEDGER - Service
  interledger:
    build:
      context: ./interledger-service
      dockerfile: Dockerfile
    container_name: interledger_service
    ports:
      - "3005:3000"
    restart: always
  ##   ☆*: .｡. o(≧▽≦)o .｡.:*☆
  ## DATA - MongoDB instance

  ## DATA - Service